apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  containers:
  - name: demo
    image: busybox
    command:
    - sh
    - -c
    - |
      while true
      do
        echo APP_NAME=$APP_NAME
        echo APP_ENV=$APP_ENV
        sleep 10
      done
    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_NAME
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_ENV